name = "debt_planner"
version = "0.0.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "metruzanca", repo = "debt_planner" }
gleam = ">= 1.6.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
