name = "app"
version = "0.0.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "metruzanca", repo = "debt_planner" }
gleam = ">= 1.6.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 1.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
tardis = ">= 0.3.0 and < 1.0.0"
glentities = ">= 6.2.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
